ipv4_servers = true
ipv6_servers = false
require_dnssec = false
require_nolog = true
require_nofilter = false
block_ipv6 = false
force_tcp = false
server_names = ['cloudflare']
disabled_server_names = []
listen_addresses = ['127.0.0.1:5354']
max_clients = 250
#user_name = '0'
dnscrypt_servers = true
doh_servers = true
timeout = 5000
keepalive = 30
netprobe_timeout = -1
#log_level = 2
#log_file = '/dev/null'
use_syslog = false
cert_refresh_delay = 240
dnscrypt_ephemeral_keys = false
tls_disable_session_tickets = false
fallback_resolver = '1.0.0.1:53'
netprobe_address = '1.0.0.1:53'
block_unqualified = true
block_undelegated = true
reject_ttl = 600
ignore_system_dns = true
#log_files_max_size = 1
#log_files_max_age = 7
#log_files_max_backups = 1
cache = false
cache_size = 4096
cache_min_ttl = 2400
cache_max_ttl = 86400
cache_neg_ttl = 60
cache_neg_max_ttl = 600
#forwarding_rules = 'forwarding-rules.txt'
#cloaking_rules = 'cloaking-rules.txt'
#proxy = 'socks5://127.0.0.1:9050'
[local_doh]
#listen_addresses = ['127.0.0.1:3000']
#path = '/dns-query'
#cert_file = 'localhost.pem'
#cert_key_file = 'localhost.pem'
[query_log]
format = 'tsv'
#file = '/dev/null'
ignored_qtypes = ['DNSKEY', 'NS']
[nx_log]
format = 'tsv'
#file = /dev/null'
[blacklist]
blacklist_file = '/etc/dnscrypt-proxy/blacklist.txt'
[ip_blacklist]
#blacklist_file = 'ip-blacklist.txt'
[whitelist]
#whitelist_file = 'whitelist.txt'
[sources]
[sources.'public-resolvers']
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/public-resolvers.md', 'https://download.dnscrypt.info/resolvers-list/v2/public-resolvers.md']
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
cache_file = 'public-resolvers.md'
refresh_delay = 72
prefix = ''
[sources.'relays']
urls = ['https://raw.githubusercontent.com/DNSCrypt/dnscrypt-resolvers/master/v2/relays.md', 'https://download.dnscrypt.info/resolvers-list/v2/relays.md']
cache_file = 'relays.md'
minisign_key = 'RWQf6LRCGA9i53mlYecO4IzT51TGPpvWucNSCh1CBM0QTaLn73Y7GFO3'
refresh_delay = 72
prefix = ''
[broken_implementations]
#fragments_blocked = ['cisco', 'cisco-ipv6', 'cisco-familyshield', 'cisco-familyshield-ipv6', 'quad9-dnscrypt-ip4-filter-alt', 'quad9-dnscrypt-ip4-filter-pri', 'quad9-dnscrypt-ip4-nofilter-alt', 'quad9-dnscrypt-ip4-nofilter-pri', 'quad9-dnscrypt-ip6-filter-alt', 'quad9-dnscrypt-ip6-filter-pri', 'quad9-dnscrypt-ip6-nofilter-alt', 'quad9-dnscrypt-ip6-nofilter-pri', 'cleanbrowsing-adult', 'cleanbrowsing-family-ipv6', 'cleanbrowsing-family', 'cleanbrowsing-security']
[anonymized_dns]
skip_incompatible = false
#routes = [
#{ server_name = 'adguard-dns', via=['anon-kama', 'anon-scaleway', 'anon-tiarap'] },
#{ server_name = 'sfw.scaleway-fr', via=['anon-ibksturm', 'anon-kama', 'anon-tiarap'] },
#{ server_name = 'oszx', via=['anon-kama', 'anon-tiarap', 'anon-scaleway'] },
#{ server_name = 'dnscrypt-sg-blahdns-ipv4', via=['anon-kama', 'anon-scaleway', 'anon-tiarap'] }
#]
[static]
